### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by anti-social** [anti-social/elasticmagic#26]
Network dependent code:

- `Cluster` & `Index` classes
- `SearchQuery`: `get_result`, `count`, `exists`, `__iter__`, `__getitem__` methods
- `SearchQueryWrapper` & `Pagination`
- `GroupedPageFilter` - possibly we don't need it anymore

**Comment by a-urth** [comment]
It would game changer since official package still has no solution to that.
https://github.com/elastic/elasticsearch-dsl-py/issues/556

**Comment by anti-social** [comment]
We have a minimum asyncio implementation for doing simple search queries in our autocomplete service. Elasticmagic documents are not active records (I think it is anti-pattern especially for big projects) so we have one problem less =)

**Comment by alxpy** [comment]
I think it's good choice for async transport — https://github.com/elastic/elasticsearch-py-async
