### ISSUE TITLE
new types._Int.to_python breaks compatibility

### ISSUE THREAD

**Issue by popravich** [anti-social/elasticmagic#5]
With this change https://github.com/anti-social/elasticmagic/commit/1a52e700ccb7f8b81c9303adecbe2a7e662d5078#diff-a9f798da5f5a761c0136dc7f3261eefcR53 introduced the compatibility (and functionality) is broken.
Before this change the code looked like this:
```python
if value is None:
    return None
```
and it was fine. Now (for example) aggregations are broken:
consider following range aggregation on integer field:
```json
{
  "aggs": {
    "prices": {
      "range": {
        "field": "price",
        "ranges": [
        { "to": 50 },
        { "from": 50, "to": 100 },
        { "from": 100 }
        ]
      }
    }
  }
}
```
The following piece of [code](https://github.com/anti-social/elasticmagic/blob/master/elasticmagic/agg.py#L426-L427) will try to conver results to python types 
but it will fail with `TypeError` becasue two of three buckets will contain both fields `to` and `from`

**Comment by anti-social** [comment]
Вернул проверку значения на None. Описание баги на 5++ =)

**Comment by popravich** [comment]
Это опен-соурс) не опишешь нормально -- не починят!
