### ISSUE TITLE
Typo in GeoPoint.to_python

### ISSUE THREAD

**Issue by popravich** [anti-social/elasticmagic#6]
I assume its a typo or is this a some kind of (elastic)magic?
[elasticmagic/types.py](https://github.com/anti-social/elasticmagic/blob/master/elasticmagic/types.py#L270-L272)
```python
  def to_python(value):
      # ...
      elif isinstance(value, dict):
          value = [value.get('lon'), value.get('lat')]
      return {'lat': float(value[0]), 'lon': float(value[1])}
```

**Comment by anti-social** [comment]
Смотрел наверное минуту - и не увидел в чем прикол =)

**Comment by popravich** [comment]
=))
